version: "3.0"
services:

  db:
    # Pinning MariaDB to point release 10.4.30 works around the issues with the
    # database migrations seen with 10.4.31 in issue #1212.
    #
    # TODO: Get database migrations to work with the latest point releases of
    # MariaDB 10.4.
    image: mariadb:latest
    networks:
      - external_net
    environment:
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_password_secret 
      #- MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #ports:
    #  - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    
volumes:
  mariadb_data:
    external: true

networks:
  external_net:
    external: true

secrets:
  mariadb_password_secret:
    external: true
