version: "3.0"
services:
  steve:
    image: eleucarlos/steve:latest
    networks:
      - external_net
    environment:
      - STEVE_BROWSER_REDIRECT_URL=${STEVE_BROWSER_REDIRECT_URL}
      - STEVE_SERVER_URL=${STEVE_SERVER_URL}
      - STEVE_API_DOMAIN=${STEVE_API_DOMAIN}
      - STEVE_SERVER_DOMAIN=${STEVE_SERVER_DOMAIN}
      - db.ip=mariadb
      - db.port=3306
      - db.schema=${MYSQL_DATABASE}
      - db.user=${MYSQL_USER}
      - db.password=${MYSQL_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.steve_http.rule=Host(`${STEVE_API_DOMAIN}`)
        - traefik.http.routers.steve_http.entrypoints=websecure
        - traefik.http.routers.steve_http.tls.certresolver=letsencryptresolver
        - traefik.http.services.steve_http.loadbalancer.server.port=8180
        - traefik.http.services.steve_http.loadbalancer.passHostHeader=true
        - traefik.http.routers.steve_http.service=steve_http
        - traefik.http.routers.steve_https.rule=Host(`${STEVE_SERVER_DOMAIN}`)
        - traefik.http.routers.steve_https.entrypoints=websecure
        - traefik.http.routers.steve_https.tls.certresolver=letsencryptresolver
        - traefik.http.services.steve_https.loadbalancer.server.port=8443
        - traefik.http.services.steve_https.loadbalancer.passHostHeader=true
        - traefik.http.routers.steve_https.service=steve_https

networks:
  external_net:
    external: true 