version: "3.0"
services:

  db:
    # Pinning MariaDB to point release 10.4.30 works around the issues with the
    # database migrations seen with 10.4.31 in issue #1212.
    #
    # TODO: Get database migrations to work with the latest point releases of
    # MariaDB 10.4.
    image: mariadb:latest
    networks:
      - external_net
    environment:
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_password_secret
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    
  steve:
    build: .
    networks:
      - external_net
    depends_on:
      - db
    environment:
      - db.ip=db
      - db.port=3306
      - db.schema=${MYSQL_DATABASE}
      - db.user=${MYSQL_USER}
      - db.password_file=/run/secrets/mariadb_password_secret
      - STEVE_BROWSER_REDIRECT_URL=${STEVE_BROWSER_REDIRECT_URL}
      - STEVE_SERVER_URL=${STEVE_SERVER_URL}
      - STEVE_API_DOMAIN=${STEVE_API_DOMAIN}
      - STEVE_SERVER_DOMAIN=${STEVE_SERVER_DOMAIN}
    ports:
      - "8180:8180"
      - "8443:8443"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.steve_http.rule=Host(`${STEVE_API_DOMAIN}`)
        - traefik.http.routers.steve_http.entrypoints=websecure
        - traefik.http.routers.steve_http.tls.certresolver=letsencryptresolver
        - traefik.http.services.steve_http.loadbalancer.server.port=8180
        - traefik.http.services.steve_http.loadbalancer.passHostHeader=true
        - traefik.http.routers.steve_http.service=steve_http
        - traefik.http.routers.steve_https.rule=Host(`${STEVE_SERVER_DOMAIN}`)
        - traefik.http.routers.steve_https.entrypoints=websecure
        - traefik.http.routers.steve_https.tls.certresolver=letsencryptresolver
        - traefik.http.services.steve_https.loadbalancer.server.port=8443
        - traefik.http.services.steve_https.loadbalancer.passHostHeader=true
        - traefik.http.routers.steve_https.service=steve_https

volumes:
  mariadb_data:
    external: true

networks:
  external_net:
    external: true

secrets:
  mariadb_password_secret:
    external: true
